project_id = "zgutgcwzakyceylzwbry"

[functions.invite-user-builtin]
verify_jwt = false

[functions.reinvite-user-builtin]
verify_jwt = false

[functions.import-legacy-data]
verify_jwt = false

[functions.populate-missing-zipcodes]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.maintenance-issue]
verify_jwt = false

[functions.maintenance-error]
verify_jwt = false

[functions.maintenance-log]
verify_jwt = false
