project_id = "zgutgcwzakyceylzwbry"

[functions.send-invite]
verify_jwt = false

[functions.resend-invite]
verify_jwt = false

[functions.import-legacy-data]
verify_jwt = false

[functions.populate-missing-zipcodes]
verify_jwt = false

[functions.delete-user]
verify_jwt = false
