// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zgutgcwzakyceylzwbry.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpndXRnY3d6YWt5Y2V5bHp3YnJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczNTEyNjYsImV4cCI6MjA3MjkyNzI2Nn0.da-8PwDuznS_-4eG74Jry8rqV2oM_f6nV3tcKQGPclY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});